language: python
python:
    - 3.6

services: postgresql

env:
    global:
        - DJANGO_SETTINGS_MODULE="fyt.settings"
        - PYTHONPATH="/home/travis/builds/rlmv/doc-trips"
        - DATABASE_URL="postgres://postgres@localhost/testdb"
        - SECRET_KEY="secret"
        # AWS_ACCESS_KEY_ID
        - secure: "enKbXvTVF9DjrX27m6o6R1bvxg879pXZQIxZRQOCO0BnvmfjkRM+fE1n2IZr/gk8p4vDYqSKqcaAabTlsfcIErWAg+W9zMFqzjYzuR6LAnqpndFcXjYYU0y6yD0PS6DBhrdSrIGvJJga99+clt4c6ry4MEe0Yu+OcF0hb4x2gExOAk/xN1uPFOBZzwd0RA9Dv1TVkoDP6OtcySfEUdhi4QiKhvmBCoTsee0+4DBk4C3CeSU8G/zcUN92PSPv1uRDDNNtt2TDRtIoWiUZepTpz33ZceF76CeDbrQOXnea7ua8b2NZTGblQci6RO+OPxrpXlhvLeCNVYqP56bR92w4fowRxfZAND7Rr1MiqyI5Xz/BxnHiziVBegN3kYrHtrmq2jae56s2sA8t3qetZjvb/Ix+rR/LeBzdXF0LB6suCtoOCbyz0jTQT0z7X5HAMDWPRXGhYVGyo5A83h0LBhLi6ToI9U4I+ok32f93y2vzBcan3QJ1YUKCPian1YItcfyLN0FFsDc7nly2lvnUeQwh8XVAv+/OzqenSgNwTaLUeKcsQtwPhRCdg/NjHTB09sinbWc0NjQIYTHhWm6XePiR507p2tkZwkVQ46JlNnxyVZXgNDrZ94ZNDOsToQos+umDbUlmZ+NG3vEnDjyki46lQ6wuHpqOgfrakkE0G3kBXeg="
        # AWS_SECRET_ACCESS_KEY
        - secure: "n4kd50U4uBBprdUzBNoQ2MlFn6wVWBwCAvEFv3edxbh0zc4P1kPD/gJ+5niasOe4NgiMx737Rx7V4gDNp3gUY9UE8LEo8/n97NYNii/QodasgVeZ9QjARQl+yELuvhx6tL/Z7baNx8RulGUB7fdCwH7J04KfTH/fuMv8r9M+Nhvha6hSqWQnT6ARgHvnuAcwOnytaweX+M7U/soKiDkjutvjQAqMvQGMOH06TrPdM96qBGCBn4Ev2HFJ//+JnJ+UeRD3ZiHlAnw1hxPQk8GdmXB6rGLuFElWsPIz1d3eTvW+7F31oQuaWOONmP2LMDTPgp+iSciTiu5bhNvQDi/FJxVVq7vDXKbU7u/8v8AeGLSGmxSkH0D+Edl7s/gga8+hvoZNXLP8m2pdC6WW/YReSUvRfB1HSj4tq38U43QYWLbgtffPsj9Pn5z7RX+5TklDTOa3S/6YsGCTtLsw5PQ76ozTnPR2h1/mZMwyecjDB2YNyXQWHwqMura4+k4jE/WLt91d08ppDtaHAUe3UIBpeLYjUH7EQQeo6wzDLSa9nXkcWRMUYfC/OMvAC6rRcxsgQp3vSwygnPSLuEkkX5o7fLwsGCOgyLD26KOWhEVYWQOZnODvZn5+/D67pBbjHEVks/CYCBA4BwP0OpfWZwhkdVuQWnlw94xHfI3sqcx3+N8="
        - AWS_STORAGE_BUCKET_NAME="doc-trips-travis-testing"
        # GOOGLE_MAPS_KEY
        - secure: "MHWAfGl977egkU2CK7cdxlSQYpchXOK+0hIwyzS8S7Fv77dKPhlZb8fRGFXngwb+Zba9Q6l6sdyE3BT3CsMG01Li/fo/zXlDV2VF2bxYvmjP7t3OWID9YBjV09nfxGKxPoLq3/s2Zzd4hctxZTnXFe5fbuV9+odGZytJi+rYS18qCU2BdLIBsgkDlRylLlzNHhI4vrnwPwgXOCryPEwdg/cA8AslXTg8sQ1RrXLfkKC0od+CcPy44Zr2hBbs8vHqiRGtffAY102ns8xsr3w/exXfBgO8p7EkRcvMefZSDfkAOm+TaaQ2a3pOLy1t/Vt8hZF7Ipv8citdq15V0wakiCbsFWXkQaDJ8sbslWtMKFX2XMiBAMc2/pHYMSHqPPkHY5RcyCgBLYWx322Z14ecHOwJUX3XSaPj7wTeQOjgCBS/OM8qOxsIOjyjzJwGBwiBPuYwcEzSz4bFluQpgp4jiySrbKsRSmzT94DkHlY3MFE5nfPPfvLDU8PAg/m7jGZQDcfcPjObwDZsPgM9fnVhi8tgfrkttXVAQZSRc9FDWhOEjtojwtfykkIBEqf5RmTIwPmdNI7x0S4dpeLo6OJq8buNGzAXmz0Nx5VdSgkXyIRnwhVa8xL3vXaYE3flV3OmInnFrmnK3UDJyh5pHBrXoizbThotromfQw21oQ3ZhQU="
        # GOOGLE_MAPS_BROWSER_KEY
        - secure: "C3tkgiTYn+ANpHGKYlNxNJd0F1J0iXu6NMtt+1FikECrO44MZGta2weyNQsw+jSx5VgUGaNZlSPAIZG6l1UYxqxS+nbHax9LmU5oeD9Nvis2ElXaoYYxqL5qvVM9hj2xlwmki9eLL+zfw5UJAEpIPy42b3GFoVNA6SEeKMdpnGA6Gs1idzU4Y8cGCGLcbAJHsJ5GaVFxB1LBNuTfqaZ9KbBAwu0tV/H/smZidhgPkSY29sKEvdOT7RGtV0Hy6NsEjEkaSNp/09ojMxHfdjSjKmwb2+UGr6hl8R11doCsL2hOCeAJ9F/4ES/iSpl4Xy1xmmwB6ukGfpXp8EivQswkcnBoubGqlD3Jnk1qjqf/T7QZNV+Nl8rScbZo64aucFMFF/f+AZuOzi5JdKKmXMg9yAiZtcA39HSeuDuQQh790ErSYnmhx+ukj1ZBVkkdhBok2uvD3KgfMEBJcxBwjn9IfmUIB65tdPAJPdaoOnU+bkdITwqu3trzXyWmDguGdjz5VCedLPwOESe8dgSNvQ+l8p9BIKnlkjeHdQQpD9uNgJ6u9HMRJaN5crcwHaHSir4QGLgxGD2Oo61EOb6pMKZdCNyr6UShyuvXkVzVuz1SEr8ThKguaa/fBguOvYhRchBFmKG7L5DRlSddqEA3kWNYRZxPYjh/9NNOpCm35fiuKD8="

install:
    - pip install -r requirements/test.txt
    - pip install psycopg2 --quiet

before_script:
    - psql -c "CREATE DATABASE testdb;" -U postgres

script: ./manage.py test

notifications:
  email:
    on_success: never
    on_failure: always
