
language: python
python:
    - 3.4

services: postgresql

env:
    - DJANGO_SETTINGS_MODULE="fyt.settings"
    - PYTHONPATH="/home/travis/builds/rlmv/doc-trips"
    - PIP_USE_MIRRORS=true
    - DATABASE_URL="postgres://testuser@localhost/testdb"
    - SECRET_KEY="secret"

install:
    - pip install -r requirements.txt
    - pip install psycopg2 --quiet

before_script:
    - psql -c "CREATE DATABASE testdb;" -U testuser

script: ./manage.py test

notifications:
  email:
    on_success: always
    on_failure: always
