
language: python
python:
    - 3.4

services: postgresql

env:
    global:
        - DJANGO_SETTINGS_MODULE="fyt.settings"
        - PYTHONPATH="/home/travis/builds/rlmv/doc-trips"
        - DATABASE_URL="postgres://postgres@localhost/testdb"
        - SECRET_KEY="secret"
        # AWS_ACCESS_KEY_ID
        - secure: "enKbXvTVF9DjrX27m6o6R1bvxg879pXZQIxZRQOCO0BnvmfjkRM+fE1n2IZr/gk8p4vDYqSKqcaAabTlsfcIErWAg+W9zMFqzjYzuR6LAnqpndFcXjYYU0y6yD0PS6DBhrdSrIGvJJga99+clt4c6ry4MEe0Yu+OcF0hb4x2gExOAk/xN1uPFOBZzwd0RA9Dv1TVkoDP6OtcySfEUdhi4QiKhvmBCoTsee0+4DBk4C3CeSU8G/zcUN92PSPv1uRDDNNtt2TDRtIoWiUZepTpz33ZceF76CeDbrQOXnea7ua8b2NZTGblQci6RO+OPxrpXlhvLeCNVYqP56bR92w4fowRxfZAND7Rr1MiqyI5Xz/BxnHiziVBegN3kYrHtrmq2jae56s2sA8t3qetZjvb/Ix+rR/LeBzdXF0LB6suCtoOCbyz0jTQT0z7X5HAMDWPRXGhYVGyo5A83h0LBhLi6ToI9U4I+ok32f93y2vzBcan3QJ1YUKCPian1YItcfyLN0FFsDc7nly2lvnUeQwh8XVAv+/OzqenSgNwTaLUeKcsQtwPhRCdg/NjHTB09sinbWc0NjQIYTHhWm6XePiR507p2tkZwkVQ46JlNnxyVZXgNDrZ94ZNDOsToQos+umDbUlmZ+NG3vEnDjyki46lQ6wuHpqOgfrakkE0G3kBXeg="
        # AWS_SECRET_ACCESS_KEY
        - secure: "n4kd50U4uBBprdUzBNoQ2MlFn6wVWBwCAvEFv3edxbh0zc4P1kPD/gJ+5niasOe4NgiMx737Rx7V4gDNp3gUY9UE8LEo8/n97NYNii/QodasgVeZ9QjARQl+yELuvhx6tL/Z7baNx8RulGUB7fdCwH7J04KfTH/fuMv8r9M+Nhvha6hSqWQnT6ARgHvnuAcwOnytaweX+M7U/soKiDkjutvjQAqMvQGMOH06TrPdM96qBGCBn4Ev2HFJ//+JnJ+UeRD3ZiHlAnw1hxPQk8GdmXB6rGLuFElWsPIz1d3eTvW+7F31oQuaWOONmP2LMDTPgp+iSciTiu5bhNvQDi/FJxVVq7vDXKbU7u/8v8AeGLSGmxSkH0D+Edl7s/gga8+hvoZNXLP8m2pdC6WW/YReSUvRfB1HSj4tq38U43QYWLbgtffPsj9Pn5z7RX+5TklDTOa3S/6YsGCTtLsw5PQ76ozTnPR2h1/mZMwyecjDB2YNyXQWHwqMura4+k4jE/WLt91d08ppDtaHAUe3UIBpeLYjUH7EQQeo6wzDLSa9nXkcWRMUYfC/OMvAC6rRcxsgQp3vSwygnPSLuEkkX5o7fLwsGCOgyLD26KOWhEVYWQOZnODvZn5+/D67pBbjHEVks/CYCBA4BwP0OpfWZwhkdVuQWnlw94xHfI3sqcx3+N8="
        - AWS_STORAGE_BUCKET_NAME="doc-trips-travis-testing"

install:
    - pip install -r requirements.txt
    - pip install psycopg2 --quiet

before_script:
    - psql -c "CREATE DATABASE testdb;" -U postgres

script: ./manage.py test

notifications:
  email:
    on_success: always
    on_failure: always
