version: '3.7'
services:
  postgres:
    hostname: postgres
    image: postgres:9.6
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: 'fyt'
      POSTGRES_USER: 'fytuser'
      POSTGRES_PASSWORD: 'password'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
